name = "lyrics-api"
main = "src/index.js"
compatibility_date = "2025-09-25"

[[d1_databases]]
binding = "DB"
database_name = "lyrics-db"
database_id = "e045426a-246b-47d1-87e9-8688ff8232b4"  # Will get from Cloudflare
